Converted the build workflow to use the new Apio workflow actions.

diff --git a/.github/workflows/build-and-release.yaml b/.github/workflows/build-and-release.yaml
--- a/.github/workflows/build-and-release.yaml
+++ b/.github/workflows/build-and-release.yaml
@@ -17,6 +17,7 @@ env:
   # These are set latter.
   RELEASE_TAG: ""
   PACKAGE_TAG: ""
+  RELEASE_COMMIT: ""
 
 jobs:
   build-and-release:
@@ -26,37 +27,49 @@ jobs:
       - name: Checkout this repo
         uses: actions/checkout@v4
 
-      - name: Install anti virus (ClamAV)
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y clamav clamav-daemon
-          sudo systemctl stop clamav-freshclam || true
-          sudo freshclam --verbose
+      # - name: Install anti virus (ClamAV)
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y clamav clamav-daemon
+      #     sudo systemctl stop clamav-freshclam || true
+      #     sudo freshclam --verbose
 
-      # E.g. "2025-11-02"
-      - name: Determine release tag
-        run: |
-          release_tag="$(date +'%Y-%m-%d')"
-          echo $release_tag
-          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV
+      # # E.g. "2025-11-02"
+      # - name: Determine release tag
+      #   run: |
+      #     release_tag="$(date +'%Y-%m-%d')"
+      #     echo $release_tag
+      #     echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV
 
-      # E.g. "20251102"
-      - name: Determine package tag
-        run: |
-          package_tag="${RELEASE_TAG//-/}"
-          echo $package_tag
-          echo "PACKAGE_TAG=$package_tag" >> $GITHUB_ENV
+      # # E.g. "20251102"
+      # - name: Determine package tag
+      #   run: |
+      #     package_tag="${RELEASE_TAG//-/}"
+      #     echo $package_tag
+      #     echo "PACKAGE_TAG=$package_tag" >> $GITHUB_ENV
 
-      - name: Determine last commit
-        run: |
-          commit=$(git rev-parse HEAD)
-          echo $commit
-          echo "RELEASE_COMMIT=$commit" >> $GITHUB_ENV
+      - name: Get release and package tags
+        uses: fpgawars/apio-workflows/.github/actions/get-release-and-package-tags@main
+        with:
+          release-tag-var: RELEASE_TAG
+          package-tag-var: PACKAGE_TAG
+
+      # - name: Determine last commit
+      #   run: |
+      #     commit=$(git rev-parse HEAD)
+      #     echo $commit
+      #     echo "RELEASE_COMMIT=$commit" >> $GITHUB_ENV
+
+      - name: Get repository commit
+        uses: fpgawars/apio-workflows/.github/actions/get-repo-commit@main
+        with:
+          repo-dir: .
+          env-var-name: RELEASE_COMMIT
 
       - name: Determine package file name
         run: |
           package_name="apio-drivers-windows-amd64-${PACKAGE_TAG}.tgz"
-          echo $package_name
+          echo "PACKAGE_NAME=$package_name"
           echo "PACKAGE_NAME=$package_name" >> $GITHUB_ENV
 
       - name: Create the build info file
@@ -79,11 +92,16 @@ jobs:
 
           cat -n build-info.json
 
-      - name: Format build info
-        run: |
-          npm install -g json-align
-          json-align --in-place --spaces 2 build-info.json
-          cat -n build-info.json
+      # - name: Format build info
+      #   run: |
+      #     npm install -g json-align
+      #     json-align --in-place --spaces 2 build-info.json
+      #     cat -n build-info.json
+
+      - name: Format build info json file in-place
+        uses: fpgawars/apio-workflows/.github/actions/format-json-file@main
+        with:
+          json-file: build-info.json
 
       - name: Copy the build info to the package
         run: |
@@ -97,6 +115,12 @@ jobs:
           popd
           ls -al
 
+      - name: Convert json build info to text
+        uses: fpgawars/apio-workflows/.github/actions/json-to-text@main
+        with:
+          input-json: build-info.json
+          output-text: build-info.txt
+
       - name: Prepare release text
         run: |
           cat  > RELEASE_BODY.txt <<EOF
@@ -104,62 +128,85 @@ jobs:
 
           Build info:
           \`\`\`
-          $(tr -d '",{}' < build-info.json)
+          $(cat build-info.txt)
           \`\`\`
           EOF
 
-          cat -n $out
-
-      # Delete old pre-releases, keeps all releases.
-      - name: Delete old pre-releases
-        uses: sgpublic/delete-release-action@v1.2
-        with:
-          # Keep all stable releases .
-          release-drop: false
-          # Delete old pre-releases, keep the newest 10 (excluding the absolute latest)
-          pre-release-drop: true
-          pre-release-keep-count: 5
-          pre-release-drop-tag: true # Also delete tags of deleted pre-releases
-          # Keep all drafts.
-          draft-drop: false
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
+          cat -n RELEASE_BODY.txt
 
       # Scans recursively inside the .tgz packages.
-      # See https://linux.die.net/man/1/clamscan
-      - name: Scan the packages for viruses
-        run: |
-          clamscan -r --verbose --scan-archive=yes apio-drivers-*.tgz
+      # # See https://linux.die.net/man/1/clamscan
+      # - name: Scan the packages for viruses
+      #   run: |
+      #     clamscan -r --verbose --scan-archive=yes apio-drivers-*.tgz
 
-      - name: Delete same tag pre-release if exist.
-        run: |
-          set -e
-          gh release list --limit 100
-          output=$(gh release view "$RELEASE_TAG" --json name,tagName,isDraft,isImmutable,isPrerelease 2>&1 || true)
-          echo $output
-          if [[ "$output" == "release not found" ]]; then
-            echo "Release $RELEASE_TAG does not exist, safe to continue."
-          elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "true" ]]; then
-            echo "Release $RELEASE_TAG exists and is a pre-release, deleting."
-            gh release delete "$RELEASE_TAG" --yes --cleanup-tag
-          elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "false" ]]; then
-            echo "Error: A stable release (non pre-release) already exists for tag $RELEASE_TAG."
-            exit 1
-          else
-            echo "Error determining if release $RELEASE_TAG exists"
-            exit 1
-          fi
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
-
-      - name: Create GitHub release
-        uses: softprops/action-gh-release@v2.2.2
+      - name: Scan the package for viruses
+        uses: fpgawars/apio-workflows/.github/actions/scan-files-for-viruses@main
         with:
-          tag_name: ${{env.RELEASE_TAG}}
-          name: ${{env.RELEASE_TAG}}
-          body_path: RELEASE_BODY.txt
-          preserve_order: true
-          prerelease: true
-          fail_on_unmatched_files: true
+          file-patterns: |
+            apio-drivers-*.tgz
+
+      # # Delete old pre-releases, keeps all releases.
+      # - name: Delete old pre-releases
+      #   uses: sgpublic/delete-release-action@v1.2
+      #   with:
+      #     # Keep all stable releases .
+      #     release-drop: false
+      #     # Delete old pre-releases, keep the newest 10 (excluding the absolute latest)
+      #     pre-release-drop: true
+      #     pre-release-keep-count: 5
+      #     pre-release-drop-tag: true # Also delete tags of deleted pre-releases
+      #     # Keep all drafts.
+      #     draft-drop: false
+      #   env:
+      #     GITHUB_TOKEN: ${{ github.token }}
+
+      # - name: Delete same tag pre-release if exist.
+      #   run: |
+      #     set -e
+      #     gh release list --limit 100
+      #     output=$(gh release view "$RELEASE_TAG" --json name,tagName,isDraft,isImmutable,isPrerelease 2>&1 || true)
+      #     echo $output
+      #     if [[ "$output" == "release not found" ]]; then
+      #       echo "Release $RELEASE_TAG does not exist, safe to continue."
+      #     elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "true" ]]; then
+      #       echo "Release $RELEASE_TAG exists and is a pre-release, deleting."
+      #       gh release delete "$RELEASE_TAG" --yes --cleanup-tag
+      #     elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "false" ]]; then
+      #       echo "Error: A stable release (non pre-release) already exists for tag $RELEASE_TAG."
+      #       exit 1
+      #     else
+      #       echo "Error determining if release $RELEASE_TAG exists"
+      #       exit 1
+      #     fi
+      #   env:
+      #     GITHUB_TOKEN: ${{ github.token }}
+
+      - name: Cleanup old pre-releases
+        uses: fpgawars/apio-workflows/.github/actions/cleanup-old-prereleases@main
+
+      - name: Ensure no conflicting release
+        uses: fpgawars/apio-workflows/.github/actions/ensure-no-conflicting-release@main
+        with:
+          release-tag: ${{ env.RELEASE_TAG }}
+
+      # - name: Create GitHub release
+      #   uses: softprops/action-gh-release@v2.2.2
+      #   with:
+      #     tag_name: ${{env.RELEASE_TAG}}
+      #     name: ${{env.RELEASE_TAG}}
+      #     body_path: RELEASE_BODY.txt
+      #     preserve_order: true
+      #     prerelease: true
+      #     fail_on_unmatched_files: true
+      #     files: |
+      #       apio-drivers-windows-amd64-${{env.PACKAGE_TAG}}.tgz
+
+      - name: Create GitHub pre-release
+        uses: fpgawars/apio-workflows/.github/actions/create-pre-release@main
+        with:
+          release_tag: ${{ env.RELEASE_TAG }}
+          body_path: RELEASE-BODY.txt
+          # We intensionally list explicitly all the expected files.
           files: |
             apio-drivers-windows-amd64-${{env.PACKAGE_TAG}}.tgz
