Changed the build workflow to fail if a stable release (non prerelease) of same date already exists.

diff --git a/.github/workflows/build-and-release.yaml b/.github/workflows/build-and-release.yaml
--- a/.github/workflows/build-and-release.yaml
+++ b/.github/workflows/build-and-release.yaml
@@ -13,6 +13,11 @@ permissions:
   # Allow release creation
   contents: write
 
+env:
+  # These are set latter.
+  RELEASE_TAG: ""
+  PACKAGE_TAG: ""
+
 jobs:
   build-and-release:
     runs-on: ubuntu-latest
@@ -120,17 +125,29 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ github.token }}
 
-      # In case we overwrite and exiting release.
-      - name: Force tag update
-        run: |
-          git tag -f ${{env.RELEASE_TAG}}
-          git push origin -f ${{env.RELEASE_TAG}}
-
       # Scans recursively inside the .tgz packages.
       # See https://linux.die.net/man/1/clamscan
       - name: Scan the packages for viruses
         run: |
           clamscan -r --verbose --scan-archive=yes apio-drivers-*.tgz
+
+      - name: Delete same tag pre-release if exist.
+        run: |
+          # Status values:
+          #   "false" - exists and is a release exists
+          #   "true"  - exists and is a pre-release
+          #   ""      - doesn't exist
+          status=$(gh release view "$RELEASE_TAG" --json isPrerelease -q .isPrerelease  || true)
+          echo "Status is [$status]"
+          if [[ "$status" == "false" ]]; then
+            echo "Error: A stable release (non pre-release) already exists for tag $RELEASE_TAG."
+            exit 1
+          elif [[ "$status" == "true" ]]; then
+            echo "Deleting existing pre-release and tag $RELEASE_TAG."
+            gh release delete "$RELEASE_TAG" --yes --cleanup-tag
+          fi
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
 
       - name: Create GitHub release
         uses: softprops/action-gh-release@v2.2.2
